# Generated by Django 2.1.5 on 2020-04-11 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_series', models.CharField(max_length=200)),
                ('series_date', models.DateTimeField(default=datetime.datetime(2020, 4, 11, 14, 29, 38, 191863), verbose_name='date published')),
                ('series_slug', models.CharField(default='series', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tutorial_slug', models.CharField(default='series', max_length=200)),
                ('tutorial_series', models.ForeignKey(default='series', on_delete=django.db.models.deletion.SET_DEFAULT, to='events.Event', verbose_name='Series')),
            ],
        ),
    ]
