# Generated by Django 2.1.5 on 2020-03-30 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 16, 43, 37, 345300), verbose_name='date published'),
        ),
    ]
