# Generated by Django 2.1.5 on 2020-04-01 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200401_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 16, 54, 21, 458666), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='file',
            field=models.FileField(default='', max_length=140, upload_to=''),
        ),
    ]
