# Generated by Django 2.1.5 on 2020-04-02 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200402_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 14, 39, 41, 828448), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='tutorial_category',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='TutorialCategory',
        ),
    ]
