# Generated by Django 2.1.5 on 2020-04-03 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200402_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='tutorial_slug',
        ),
        migrations.RemoveField(
            model_name='tutorialseries',
            name='tutorial_category',
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='series_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 14, 37, 1, 465270), verbose_name='date published'),
        ),
    ]
