# Generated by Django 2.1.5 on 2020-04-03 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200403_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='tutorial_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 14, 47, 15, 53477), verbose_name='date published'),
        ),
    ]
