# Generated by Django 2.1.5 on 2020-04-04 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200404_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 14, 37, 6, 223199), verbose_name='date published'),
        ),
    ]
