# Generated by Django 2.1.5 on 2020-04-04 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200404_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tutorial_slug',
            new_name='series_slug',
        ),
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 14, 58, 42, 36913), verbose_name='date published'),
        ),
    ]
