# Generated by Django 2.1.5 on 2020-04-04 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200404_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='tutorial_slug',
        ),
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 15, 8, 17, 714116), verbose_name='date published'),
        ),
    ]
