# Generated by Django 2.1.5 on 2020-04-04 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200404_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='tutorial_series',
        ),
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 17, 1, 40, 572051), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='TutorialSeries',
        ),
    ]
