# Generated by Django 2.1.5 on 2020-04-04 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200404_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialseries',
            options={'verbose_name_plural': 'series'},
        ),
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 2, 58, 51, 252612), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='tutorial_series',
            field=models.ForeignKey(default='series', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TutorialSeries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='tutorial_slug',
            field=models.CharField(default='series', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='series_slug',
            field=models.CharField(default='series', max_length=200),
        ),
    ]
