# Generated by Django 2.1.5 on 2020-04-04 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200405_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='tutorial_slug',
        ),
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 3, 51, 9, 176367), verbose_name='date published'),
        ),
    ]
