# Generated by Django 2.1.5 on 2020-04-05 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200405_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='tutorial_slug',
            field=models.CharField(default='series', max_length=200),
        ),
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 19, 54, 37, 76806), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
