# Generated by Django 2.1.5 on 2020-04-10 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200410_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 3, 16, 3, 11970), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='series_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 3, 16, 2, 971969), verbose_name='date published'),
        ),
    ]
