# Generated by Django 2.1.5 on 2020-05-04 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200411_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', max_length=140, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='disco',
            name='file',
        ),
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 3, 6, 28, 299462), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='series_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 3, 6, 28, 276462), verbose_name='date published'),
        ),
    ]
