# Generated by Django 2.1.5 on 2020-05-04 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200505_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 3, 8, 14, 895601), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='series_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 3, 8, 14, 875600), verbose_name='date published'),
        ),
    ]
